languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Mason Computers"
# logo = "images//logo.jpg"
description = "My awesome website"
copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Elliot Mason"
  image = "images/author.png"
  headline = "Fullstack | Maker | CypherPunk"
  bio = ""
  links = [
  #   { dev = "https://dev.to/username" },
  { github = "https://github.com/CyberAstronaut101" },
  #   { hashnode = "https://username.hashnode.dev" },
  { linkedin = "https://www.linkedin.com/in/emason101/" },
  #   { medium = "https://medium.com/username" },
  #   { twitter = "https://twitter.com/username" },
  ]
