---
deployment:
      tasks:
        - export DEPLOYPATH=/home/masoncom/public_html  # Add /<app_folder> if required
        - /bin/cp -r * images $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        - /bin/cp -r * css $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        - /bin/cp -r * docs $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        - /bin/cp index.html $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH



        
        